package deawio.model;

import java.util.Date;

public class DealModel {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.deal_id
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Integer dealId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.created
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Date created;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.modified
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Date modified;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.url
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private String url;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.high_price
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Double highPrice;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.low_price
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Double lowPrice;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.discount
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Double discount;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.store_id
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Integer storeId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * deal.product_id
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Integer productId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.deal_id
   *
   * @return the value of deal.deal_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Integer getDealId() {
    return dealId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.deal_id
   *
   * @param dealId the value for deal.deal_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setDealId(Integer dealId) {
    this.dealId = dealId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.created
   *
   * @return the value of deal.created
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Date getCreated() {
    return created;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.created
   *
   * @param created the value for deal.created
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setCreated(Date created) {
    this.created = created;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.modified
   *
   * @return the value of deal.modified
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Date getModified() {
    return modified;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.modified
   *
   * @param modified the value for deal.modified
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setModified(Date modified) {
    this.modified = modified;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.url
   *
   * @return the value of deal.url
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.url
   *
   * @param url the value for deal.url
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.high_price
   *
   * @return the value of deal.high_price
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Double getHighPrice() {
    return highPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.high_price
   *
   * @param highPrice the value for deal.high_price
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setHighPrice(Double highPrice) {
    this.highPrice = highPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.low_price
   *
   * @return the value of deal.low_price
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Double getLowPrice() {
    return lowPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.low_price
   *
   * @param lowPrice the value for deal.low_price
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setLowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.discount
   *
   * @return the value of deal.discount
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Double getDiscount() {
    return discount;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.discount
   *
   * @param discount the value for deal.discount
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setDiscount(Double discount) {
    this.discount = discount;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.store_id
   *
   * @return the value of deal.store_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Integer getStoreId() {
    return storeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.store_id
   *
   * @param storeId the value for deal.store_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setStoreId(Integer storeId) {
    this.storeId = storeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column deal.product_id
   *
   * @return the value of deal.product_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Integer getProductId() {
    return productId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column deal.product_id
   *
   * @param productId the value for deal.product_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setProductId(Integer productId) {
    this.productId = productId;
  }
}
