package deawio.model;

import java.util.Date;

public class ProductModel {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * product.product_id
   *
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  private Integer productId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * product.created
   *
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  private Date created;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * product.modified
   *
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  private Date modified;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * product.name
   *
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * product.code
   *
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  private String code;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * product.image_url
   *
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  private String imageUrl;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column product.product_id
   *
   * @return the value of product.product_id
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public Integer getProductId() {
    return productId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column product.product_id
   *
   * @param productId the value for product.product_id
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column product.created
   *
   * @return the value of product.created
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public Date getCreated() {
    return created;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column product.created
   *
   * @param created the value for product.created
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public void setCreated(Date created) {
    this.created = created;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column product.modified
   *
   * @return the value of product.modified
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public Date getModified() {
    return modified;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column product.modified
   *
   * @param modified the value for product.modified
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public void setModified(Date modified) {
    this.modified = modified;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column product.name
   *
   * @return the value of product.name
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column product.name
   *
   * @param name the value for product.name
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column product.code
   *
   * @return the value of product.code
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column product.code
   *
   * @param code the value for product.code
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public void setCode(String code) {
    this.code = code;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column product.image_url
   *
   * @return the value of product.image_url
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public String getImageUrl() {
    return imageUrl;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column product.image_url
   *
   * @param imageUrl the value for product.image_url
   * @mbg.generated Wed Jan 24 21:36:03 GMT 2018
   */
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }
}
