package deawio.model;

import java.util.Date;

public class StoreModel {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * store.store_id
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Integer storeId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * store.created
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Date created;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * store.modified
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private Date modified;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * store.name
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * store.currency
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  private String currency;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column store.store_id
   *
   * @return the value of store.store_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Integer getStoreId() {
    return storeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column store.store_id
   *
   * @param storeId the value for store.store_id
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setStoreId(Integer storeId) {
    this.storeId = storeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column store.created
   *
   * @return the value of store.created
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Date getCreated() {
    return created;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column store.created
   *
   * @param created the value for store.created
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setCreated(Date created) {
    this.created = created;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column store.modified
   *
   * @return the value of store.modified
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public Date getModified() {
    return modified;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column store.modified
   *
   * @param modified the value for store.modified
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setModified(Date modified) {
    this.modified = modified;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column store.name
   *
   * @return the value of store.name
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column store.name
   *
   * @param name the value for store.name
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column store.currency
   *
   * @return the value of store.currency
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public String getCurrency() {
    return currency;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column store.currency
   *
   * @param currency the value for store.currency
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  public void setCurrency(String currency) {
    this.currency = currency;
  }
}
