package deawio.mapper;

import deawio.model.ProductModel;
import deawio.model.ProductModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductModelMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  long countByExample(ProductModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int deleteByExample(ProductModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int deleteByPrimaryKey(Integer productId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int insert(ProductModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int insertSelective(ProductModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  List<ProductModel> selectByExample(ProductModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  ProductModel selectByPrimaryKey(Integer productId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByExampleSelective(
      @Param("record") ProductModel record, @Param("example") ProductModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByExample(
      @Param("record") ProductModel record, @Param("example") ProductModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByPrimaryKeySelective(ProductModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * product
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByPrimaryKey(ProductModel record);
}
