package deawio.mapper;

import deawio.model.StoreModel;
import deawio.model.StoreModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreModelMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  long countByExample(StoreModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int deleteByExample(StoreModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int deleteByPrimaryKey(Integer storeId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int insert(StoreModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int insertSelective(StoreModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  List<StoreModel> selectByExample(StoreModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  StoreModel selectByPrimaryKey(Integer storeId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByExampleSelective(
      @Param("record") StoreModel record, @Param("example") StoreModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByExample(
      @Param("record") StoreModel record, @Param("example") StoreModelExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByPrimaryKeySelective(StoreModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * store
   *
   * @mbg.generated Sat Jan 13 07:44:22 GMT 2018
   */
  int updateByPrimaryKey(StoreModel record);
}
